# Generated by Django 4.1.5 on 2023-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPerris', '0002_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default='fotos/default.jpg', null=True, upload_to='fotos'),
        ),
    ]
